### PR TITLE
Added Legend Text support. Added automatic escaping of Tex special characters.

### PR DESCRIPTION
**Pull request by jamescamdenmartin**
For MATLAB 2017, the Legend text is now replaced with the psfrag command.

The special characters that the MATLAB TeX interpreter renders, such as \mu, are now automatically put in math mode, so become $\mu$.

### CODE REVIEW

**Comment by wspr** [comment]
@jamescamdenmartin — thanks for the contribution. Have you contacted the original matlabfrag author at https://github.com/zprime/matlabfrag ? It might be best to submit there first (no need to close this until you hear back, though).

**Comment by jamescamdenmartin** [comment]
The original author did get back to me, thanks!

**Comment by fips12** [comment]
Thanks for updating matlabfrag. I tried your update but I am not able to compile it. I always get a warning from pstool and the execution stopps. I hope you can help me!

> Package pstool Warning: Execution failed during process: latex -shell-escape -output-format=dvi -output-directory="./" -interaction=batchmode "TEMP344-pstool.tex"

[test.zip](https://github.com/wspr/matlabfrag/files/1739950/test.zip)

**Comment by wspr** [comment]
@fips12 — this repository is only a fork of matlabfrag and probably won't be updated further (I'll delete the fork shortly, I suspect). Your problem is because of the following line in the .tex file written by matlabfrag:

    \psfrag{016}[tc][tc]{\matlabtextA yabdd $F_x $\phi$$}%

It should be:

    \psfrag{016}[tc][tc]{\matlabtextA yabdd $F_x \phi$}%

(or similar). Are you sure this is a matlabfrag problem?

**Comment by fips12** [comment]
I would say yes, because in my Matlab-Code it says $F_x \phi$ and matlabfrag adds the other two $ signs. I guess because of the \.

**Comment by wspr** [comment]
@fips12 — sounds like it could be. I suggest opening this as a new issue on the official matlabfrag repo (https://github.com/zprime/matlabfrag).

**Pull request closed without merging**
